version: '2'

services:
    app:
        build: app
        ports:
            - "8080:80"
            - "8443:443"
            - "9000:9000"
        environment:
            - TZ=Asia/Tokyo
            - LANG=ja_JP.UTF-8
            - DBSERVER=db
            - DBUSER=postgres
            - MAIL_HOST=mail
            - COMPOSER_PROCESS_TIMEOUT=2000
            - ROOT_URLPATH=/ec-cube/html
        links:
            - postgres:db
        volumes:
            - eccube_data:/var/www/html/ec-cube

    postgres:
        build: postgres
        environment:
            - TZ=Asia/Tokyo
            - LANG=ja_JP.UTF-8
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    mail:
        image: schickling/mailcatcher
        ports:
            - "1080:1080"
            
    sftp:
        image: atmoz/sftp
        privileged: true
        ports:
            - "2222:22"
        command: 'sftp:pass:33:33:upload'
        volumes:
             - eccube_data:/home/sftp/upload

volumes:
    postgres_data:
    eccube_data:
